### ISSUE TITLE
Layouts not working after updat to 3.2.2

### ISSUE THREAD

**Issue by mennoswaak** [joomlaboat/custom-tables#74]
After update to version 3.2.2 there is an error message:
Too few arguments to function CustomTables\database::loadColumn(), 1 passed in /home/permacultuurnet/permacultuur.net/administrator/components/com_customtables/models/fields/ctlayouttype.php on line 43 and at least 3 expected 
The list of the layouts is not showing

I am on J4.4.1 and PHP 8.2.7

I found this on two different sites

**Comment by joomlaboat** [comment]
Hello Menno, please install an update from here. I already fixed it.

**Comment by joomlaboat** [comment]
Please update both the component and the Plugin. v3.2.3

**Comment by mennoswaak** [comment]
that did not help, still the same

**Comment by mennoswaak** [comment]
Can this help?

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_customtables/libraries/ct-database-joomla.php:390
2 | CustomTables\database::loadColumn() | JROOT/administrator/components/com_customtables/models/fields/ctlayouttype.php:43
3 | JFormFieldCTLayoutType->getOptions() | JROOT/libraries/src/Form/Field/ListField.php:63
4 | Joomla\CMS\Form\Field\ListField->getInput() | JROOT/libraries/src/Form/FormField.php:471
5 | Joomla\CMS\Form\FormField->__get() | JROOT/libraries/src/Form/Field/ListField.php:233
6 | Joomla\CMS\Form\Field\ListField->__get() | JROOT/layouts/joomla/searchtools/default/filters.php:35
7 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
8 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/FileLayout.php:637
9 | Joomla\CMS\Layout\FileLayout->sublayout() | JROOT/layouts/joomla/searchtools/default.php:97
10 | include() | JROOT/libraries/src/Layout/FileLayout.php:128
11 | Joomla\CMS\Layout\FileLayout->render() | JROOT/libraries/src/Layout/LayoutHelper.php:76
12 | Joomla\CMS\Layout\LayoutHelper::render() | JROOT/administrator/components/com_customtables/views/listoflayouts/tmpl/default_quatro.php:30
13 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:415
14 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:203
15 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/administrator/components/com_customtables/views/listoflayouts/view.html.php:79
16 | CustomtablesViewListoflayouts->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
17 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/administrator/components/com_customtables/controller.php:73
18 | CustomtablesController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
19 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_customtables/customtables.php:46
20 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
21 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
22 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
23 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
24 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
25 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
26 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
27 | require_once() | JROOT/administrator/index.php:32

**Comment by joomlaboat** [comment]
I know what is it.

This file is old and no longer needed:

/administrator/components/com_customtables/models/fields/ctlayouttype.php

Please delete it or uninstall the Custom Tables component and install it again.

**Comment by mennoswaak** [comment]
thanks Ivan
it is fine now
